# Generated by Django 4.2.2 on 2023-09-27 16:22

from django.db import migrations,models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20230927_1622'),
    ]

    operations = [
         migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
