# Generated by Django 4.2.2 on 2023-09-27 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_doctor_bloodgroup_doctor_doc_license_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
