# Generated by Django 4.2.2 on 2023-09-27 11:26

import uuid

from django.db import migrations, transaction

def gen_uuid(apps, schema_editor):
    Appointment = apps.get_model("hospital", "Appointment")
    for row in Appointment.objects.all():
        row.appointment_id = uuid.uuid4()
        row.save(update_fields=["appointment_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_add_appointment_id'),
    ]

    operations = [
       # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
